image: node:boron-alpine

stages:
  - build
  - test
  - deploy
  - cleanup

before_script:
  #- apk update
  #- apk add ruby libxml2-dev libxslt-dev
  #- apk add bash xvfb chromium build-base
  - apt update
  - apt install -yqq ruby libxml2-dev libxslt-dev
  - apt install -yqq bash xvfb chromium-browser build-essential
  - npm install -g reaction-cli
  - Xvfb :99 &
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="/usr/bin/chromium-browser"
    #- export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
    #- npm explore -g lighthouse -- ./lighthouse-core/scripts/download-chrome.sh
    #- mv $(npm root -g)/lighthouse/chrome-linux .
  - $LIGHTHOUSE_CHROMIUM_PATH --version


build:
  script:
    - reaction init

test:
  script:
    - reaction test

deploy:
  script:
    - echo 'this is not a deploy'

cleanup:
  script:
    - echo 'this is not a cleanup...'

